name: Spring Boot CI

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Give permission to Maven wrapper
        run: chmod +x mvnw

      - name: Build application
        run: ./mvnw clean package

      - name: Run tests
        run: ./mvnw test